update=Sat 09 Jul 2016 13:41:09 BST
last_client=kicad
[eeschema]
version=1
LibDir=../../../dev_ext/kicad-library-joeferner
[eeschema/libraries]
LibName1=igrow-101-rescue
LibName2=conn
LibName3=nordicsemi
LibName4=dc-dc
LibName5=device
LibName6=power
LibName7=linear
LibName8=adc-dac
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
